libpwquality/libpwquality

python/Makefile.am

added python patch to allow multiple python versions build without duplicating source tree.
originates from [pld-linux/libpwquality](https://github.com/pld-linux/libpwquality/commit/3cc44c3221f5702a7c38394bc63028eea18b8853)

use separate build tree for python versions

---

doc/man/pwquality.conf.5.pod
src/pam_pwquality.c
src/pwqprivate.h
src/pwquality.conf
src/pwquality.h
src/settings.c

- retry, enforce_for_root, local_users_only options can now be configured in pwquality.conf
- Fixes RHBZ#1537240

Move retry, enforce_for_root, local_users_only options to pwquality.conf

---

python/MANIFEST.in
python/setup.py.in

With these changes it is possible to do a `python setup.py sdist` in the
python subdirectory and create a tarball which can be pushed to pypi.
That will allow people to pip install the Python extension module for
libpwquality (for instance, if their distribution is not building the
extension for their version of python)
Example of building:
```
./autogen.sh
./configure
cd python
python setup.py sdist upload
```
Note that you'll need to setup pypi credentials before it will let you upload.
Example of installing:
```
pip3 install --user pwquality
```
I ran into this trying to test some software via travis ci.  Travis uses Ubuntu images and Debian/Ubuntu only has the python bindings built for Python2.  If this change is applied and the python bindings are uploaded to pypi, then people can …

Changes to allow building a tarball of the python extension

---

doc/man/pwquality.3.pod

The macro exists and is apparently supposed to be used for this, hence
use it.

man: use PWQ_MAX_ERROR_MESSAGE_LEN for sizing error buffer in example

---

src/pwquality.h

pwquality_strerror() uses size_t in the prototype, but pwquality.h
doesn't include sys/types.h is hence not self-sufficient. Fix that.

include: include sys/types.h in pwquality.h

---

src/settings.c

It's sometimes usuful to know the dictionary used by the cracklib
invocation hidden in libpwquality (for example to gracefully disable
such checks in some environments that lack the dictionary file
automatically). Right now, this is not queriable however, and
libpwquality only allows to query the setting configured in libpwquality
itself. Let's fix that and expose the cracklib built-in path, too, if
nothing was explicitly configured otherwise.

cracklib: return built-in cracklib dictionary when queried

---

doc/man/pam_pwquality.8.pod
doc/man/pwquality.conf.5.pod
src/check.c
src/pwqprivate.h
src/pwquality.conf
src/pwquality.h
src/settings.c

Check for substrings of N characters from the username. Potentially useful for sites with usernames like firstnamelastname or similar.
Also rename usercheck to "wordcheck" (and corresponding internal var names) since it's also used for arbitrary words :)
Signed-off-by: Danny Sauer <dsauer@suse.com>

Add usersubstr check

---

configure.ac

Libcrack depends on libz, when compiling the lib statically, this
dependency needs to be provided explicitly otherwise gcc will complain
about missing symbols.

fixup static compilation

---

configure.ac
src/check.c
src/generate.c
src/pwqprivate.h
src/settings.c

Check for cracklib by default but leave the option to disable it.
closes https://github.com/libpwquality/libpwquality/issues/4

Add --without-cracklib configure parameter

---

po/ja.po

I found three apparent typos at two lines in Japanese .po file.
- "短すぎます" => "短**か**すぎます"
- "エン**ピ**ロピー" => "エン**ト**ロピー"
- "小すぎます" => "小**さ**すぎます"

Fix apparent Japanese typo.

---

doc/man/pam_pwquality.8.pod

I was using the man page and it took me a bit to realize the usersubstr was referring to a substring of the user name.
This is minor but I feel it'll make it easier to understand it on first read.

Change "usersubstr" option to make it easier to understand

---

src/pam_pwquality.c

After 9084c1b032161cdb53d5f66132a91bdc207faecf, one gets:
```
pam_pwquality.c: In function 'check_local_user':
pam_pwquality.c:102:16: error: implicit declaration of function 'pam_modutil_check_user_in_passwd' [-Werror=implicit-function-declaration]
102 |         return pam_modutil_check_user_in_passwd(pamh, user, NULL) == PAM_SUCCESS;
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [Makefile:634: pam_pwquality.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```
We need to include security/pam_modutil.h when appropriate.
Signed-off-by: Sam James <sam@gentoo.org>

pam_pwquality: add include for pam_modutil_check_user_in_passwd

---

libpwquality.spec.in
python/Makefile.am
python/setup.py.in

distutils is removed from Python 3.12+:
https://peps.python.org/pep-0632/

Use setuptools instead of distutils

---

src/check.c

When setting maxclassrepeat=1, the rule would be inactive and allow passwords containing 2 consecutive characters from the same class. Only when setting maxclassrepeat>=2, the rule would behave as expected.
This issue was already addressed in pam_cracklib many years ago: https://github.com/linux-pam/linux-pam/pull/9

Make maxclassrepeat=1 behavior consistent with docs

---

src/generate.c

If the CrackLib dictionaries were missing, `pwmake(1)` would complain that the entropy is too low:
```ShellSession
$ pwmake 64
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Error: Password generation failed - required entropy too low for
settings
```
... and confuse users [1].
This changes it to report something closer to the truth:
```ShellSession
$ pwmake 64
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
Error: The password fails the dictionary check
```
... so that users can help themselves by installing the …

pwquality_generate(): Don't report CrackLib errors as 'low entropy'

---

src/pwqprivate.h
src/pwquality.h
src/settings.c

Fix #23 
I'm using `signed char` instead of `bool` because I wasn't sure if I should `#include <stdbool.h>`.

Support snippets in /usr/lib/security

---

configure.ac

AC_CHECK_FUNC didn't link libpam, so the check would ~never succeed.

configure.ac: fix pam_modutil_check_user_in_passwd check

---

src/pam_pwquality.c

The header file libintl.h has been included by config.h with macro ENABLE_NLS.It is redundant inclusion in pam_pwquality.
Fix #59

Remove redundant inclusion of libintl.h in pam_pwquality.c

---

src/pwmake.c

The commit aeff47d had changed the return value of pwquality_generate(). 
Now, the positive return value is the score of the password, not the error. 
Fix the issue like this:
$ pwmake 64
Error: Unknown error
Fix #100

Fix the error in handling the return value of the pwquality_generate function

---

configure.ac
src/generate.c

Use explicit-bzero instead of memset to clear entropy memory.
Fix #92

Effectively clear sensitive data memory
